import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const allowedThemes = new Set(["light", "dark", "sepia"]);

const readerThemeScript = `
(() => {
  try {
    const stored = localStorage.getItem("reader-theme");
    if (!stored) {
      return;
    }
    if (stored !== "light" && stored !== "dark" && stored !== "sepia") {
      return;
    }
    document.documentElement.dataset.readerTheme = stored;
  } catch (error) {
    // ignore
  }
})();
`;

async function fetchServerTheme(): Promise<string | undefined> {
  try {
    const response = await fetch(`${API_BASE}/settings`, { cache: "no-store" });
    if (!response.ok) {
      return undefined;
    }
    const data = (await response.json()) as { settings?: { theme?: string } };
    const theme = data?.settings?.theme;
    if (theme && allowedThemes.has(theme)) {
      return theme;
    }
    return undefined;
  } catch (error) {
    return undefined;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieTheme = cookieStore.get("reader-theme")?.value;
  const resolvedTheme =
    cookieTheme && allowedThemes.has(cookieTheme) ? cookieTheme : await fetchServerTheme();

  return (
    <html lang="en" data-reader-theme={resolvedTheme ?? undefined}>
      <head>
        <Script id="reader-theme-bootstrap" strategy="beforeInteractive">
          {readerThemeScript}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
